In [9]:
from sklearn.preprocessing import Imputer
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [10]:
dataset = pd.read_csv('DataPreprocessing.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(X[:, 1:])

[[49.0 86400.0]
 [32.0 57600.0]
 [35.0 64800.0]
 [43.0 73200.0]
 [45.0 nan]
 [40.0 69600.0]
 [nan 62400.0]
 [53.0 94800.0]
 [55.0 99600.0]
 [42.0 80400.0]]


In [12]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(X[:, 1:])
X[:, 1:] = imputer.transform(X[:, 1:])

In [15]:
imputer.transform([[np.nan, 80000]])

array([[4.37777778e+01, 8.00000000e+04]])

In [18]:
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
X

array([[1, 49.0, 86400.0],
       [0, 32.0, 57600.0],
       [2, 35.0, 64800.0],
       [0, 43.0, 73200.0],
       [2, 45.0, 76533.33333333333],
       [1, 40.0, 69600.0],
       [0, 43.77777777777778, 62400.0],
       [1, 53.0, 94800.0],
       [2, 55.0, 99600.0],
       [1, 42.0, 80400.0]], dtype=object)

In [19]:
oneHotEncoder = OneHotEncoder(categorical_features=[0])
X = oneHotEncoder.fit_transform(X).toarray()

/home/ds/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [20]:
X

array([[0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.90000000e+01,
        8.64000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.20000000e+01,
        5.76000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.50000000e+01,
        6.48000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.30000000e+01,
        7.32000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 4.50000000e+01,
        7.65333333e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.96000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.37777778e+01,
        6.24000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.30000000e+01,
        9.48000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 5.50000000e+01,
        9.96000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.20000000e+01,
        8.04000000e+04]])

In [21]:
labelEncoder_y = LabelEncoder()
y = labelEncoder_y.fit_transform(y)

In [22]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [23]:
scaler_X = StandardScaler()
X = scaler_X.fit_transform(X)
X

array([[-0.65465367,  1.22474487, -0.65465367,  0.75887436,  0.74947325],
       [ 1.52752523, -0.81649658, -0.65465367, -1.71150388, -1.43817841],
       [-0.65465367, -0.81649658,  1.52752523, -1.27555478, -0.89126549],
       [ 1.52752523, -0.81649658, -0.65465367, -0.11302384, -0.25320042],
       [-0.65465367, -0.81649658,  1.52752523,  0.17760889,  0.        ],
       [-0.65465367,  1.22474487, -0.65465367, -0.54897294, -0.52665688],
       [ 1.52752523, -0.81649658, -0.65465367,  0.        , -1.0735698 ],
       [-0.65465367,  1.22474487, -0.65465367,  1.34013983,  1.38753832],
       [-0.65465367, -0.81649658,  1.52752523,  1.63077256,  1.75214693],
       [-0.65465367,  1.22474487, -0.65465367, -0.25834021,  0.29371249]])

In [ ]:
# Data and resource:
# https://github.com/tarunlnmiit/machine_learning/blob/master/DataPreprocessing.csv
# https://scikit-learn.org